### PR TITLE
Migrate to Fluentd v1 API

### PR DESCRIPTION
**Pull request by okkez**
Please read "Updating Plugins Overview" before release
new version of this plugin.

See https://docs.fluentd.org/v1.0/articles/plugin-update-from-v0.12

### CODE REVIEW

**Comment by okkez** [comment]
Do I need fixing code to pass rubocop checks?

**Comment by jkohen** [comment]
@qingling128 Is this something we want to have?

**Comment by qingling128** [comment]
@jkohen - Yes. We should include this in `2.0.0` as well.

**Comment by Cryptophobia** [comment]
This is needed to allow implementations to use fluentd gracefulReload API endpoint. Will fix this issue https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions/issues/77 .

Can we get some priority on getting this merged?

**Comment by Cryptophobia** [comment]
Please close this one as it does not conform to latest code changes since the PR is old. 

#93 is tested and working with latest code. I fixed rake test errors and all tests passing on ruby 2.7.4 . Going to test this out in dev, staging. :shipit:

**Pull request closed without merging**
